import"./assets/styles-JE8YjOlG.js";import{a as d,i as l}from"./assets/vendor-4yCzdkXl.js";const C="https://dummyjson.com/",a=12,p={categories:"products/category-list",products:"products"};d.defaults.baseURL=C;async function h(){const{data:t}=await d(p.categories);return t}async function g(t){const o=(t-1)*a,e={params:{limit:a,skip:o}},{data:r}=await d(p.products,e);return r}async function _(t,o=1){const e=(o-1)*a,r={params:{limit:a,skip:e}},{data:n}=await d(`${p.products}/category/${t}`,r);return n}const s={categoryList:document.querySelector("ul.categories"),productsList:document.querySelector(".products"),loadMoreBtn:document.querySelector(".load-more-btn"),notFound:document.querySelector(".not-found")};function v(t){const o=t.map(e=>`
<li class="categories__item">
   <button class="categories__btn" type="button">${e}</button>
 </li>`).join("");s.categoryList.innerHTML=o}function L(t){const o=t.map(({id:e,thumbnail:r,title:n,brand:m,category:y,price:b})=>`
       <li class="products__item" data-id="${e}">
    <img class="products__image" src="${r}" alt="${n}"/>
    <p class="products__title">${n}</p>
    <p class="products__brand"><span class="products__brand--bold">Brand: ${m}</span></p>
    <p class="products__category">Category: ${y}</p>
    <p class="products__price">Price: ${b}$</p>
 </li>`).join("");s.productsList.insertAdjacentHTML("beforeend",o)}function f(){s.loadMoreBtn.classList.remove("is-hidden")}function i(){s.loadMoreBtn.classList.add("is-hidden")}function M(){const t=document.querySelector(".categories__btn");t&&t.classList.add("categories__btn--active")}let c=1,u="ALL";async function A(){try{const t=await h();v(["All",...t]),M()}catch(t){console.log(t),l.error({message:"Error!"})}}async function B(){try{const t=await g(c);s.productsList.innerHTML="",L(t.products),t.total>a?f():i()}catch(t){console.log(t),l.error({message:"Error!"})}}async function $(){try{c+=1;let t;u.toUpperCase()==="ALL"?t=await g(c):t=await _(u,c),L(t.products),c*a>=t.total&&i()}catch{l.error({message:"Error!"})}}function w(t){document.querySelectorAll(".categories__btn").forEach(o=>o.classList.remove("categories__btn--active")),t.classList.add("categories__btn--active")}async function E(t){const o=t.target.closest(".categories__btn");if(!o)return;const e=o.textContent.trim();u=e.toUpperCase(),c=1,w(o),i(),s.notFound.classList.remove("not-found--visible");let r;if(e.toUpperCase()==="ALL"?(r=await g(c),f()):(r=await _(e,c),i()),!r.products.length){s.notFound.classList.add("not-found--visible"),s.productsList.innerHTML="";return}s.productsList.innerHTML="",L(r.products)}A();B();s.loadMoreBtn.addEventListener("click",$);s.categoryList.addEventListener("click",E);
//# sourceMappingURL=index.js.map
